
name: run-docker

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  container:
    runs-on: ubuntu-latest
    container: simple:latest
    steps:
      - name: Run my simple image
      - uses: docker://raiyanyahya/simple-docker-github-action/simple:latest
        with:
          #entrypoint: /opt/box/box
          args: 'input'
      
